In [1]:
import numpy as np
import pandas as pd

In [2]:
#to read data
df=pd.read_csv("Social_Network_Ads.csv")
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
#drop the userid and gender because its non numeric
x=df.drop(['User ID','Gender'],axis=1)
x

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [4]:
x.dtypes

Age                int64
EstimatedSalary    int64
Purchased          int64
dtype: object

In [5]:

y=df['Purchased']
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=9) 
#in random state we can take any value, when random state is changed the accuracy will also change


In [8]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
std=StandardScaler()
x_train=std.fit_transform(x_train)
x_test=std.fit_transform(x_test)

In [9]:
x_train

array([[-0.61696196, -1.63544915, -0.72307858],
       [-0.23729306,  0.78219697,  1.38297555],
       [ 0.71187919, -1.42906472,  1.38297555],
       [-0.90171364,  0.54632906, -0.72307858],
       [-0.04745861,  2.16792097,  1.38297555],
       [-0.23729306, -0.16127469, -0.72307858],
       [ 0.99663086, -1.04577936,  1.38297555],
       [-0.99663086, -0.36765911, -0.72307858],
       [ 0.23729306,  0.04510974, -0.72307858],
       [ 0.99663086,  2.0794705 , -0.72307858],
       [-1.47121698, -0.22024166, -0.72307858],
       [ 1.09154808, -1.25216379,  1.38297555],
       [-0.99663086, -1.4880317 , -0.72307858],
       [-0.99663086,  0.57581255, -0.72307858],
       [ 0.23729306, -0.16127469, -0.72307858],
       [-1.09154808, -1.13422983, -0.72307858],
       [ 1.56613421, -1.31113077,  1.38297555],
       [-1.09154808,  0.31046114, -0.72307858],
       [ 2.04072033,  0.1630437 ,  1.38297555],
       [-1.75596866, -0.01385724, -0.72307858],
       [ 1.94580311,  0.72322999,  1.382

In [10]:
x_test

array([[-0.98673917,  0.33284989, -0.81649658],
       [-1.66926626, -1.50015214, -0.81649658],
       [ 0.67082663, -1.20919944,  1.22474487],
       [-0.30421208,  0.10008773, -0.81649658],
       [-1.18174691, -0.71457984, -0.81649658],
       [ 0.7683305 , -1.1510089 ,  1.22474487],
       [ 0.18330728,  0.21646881, -0.81649658],
       [-0.30421208,  0.15827827, -0.81649658],
       [ 0.86583437,  2.22404247,  1.22474487],
       [ 0.7683305 ,  0.18737354, -0.81649658],
       [ 1.64586533,  1.81670868,  1.22474487],
       [-1.37675465, -0.3654366 , -0.81649658],
       [-0.01170046,  0.36194516, -0.81649658],
       [ 1.15834598, -0.91824673,  1.22474487],
       [-1.18174691, -0.947342  , -0.81649658],
       [ 1.45085759,  0.129183  ,  1.22474487],
       [-0.79173143,  0.56561206, -0.81649658],
       [ 0.18330728, -0.19086497, -0.81649658],
       [-1.47425852, -1.1510089 , -0.81649658],
       [ 0.08580341,  0.82746949,  1.22474487],
       [-1.57176239,  0.39104043, -0.816

In [11]:
y_train

155    0
249    1
20     1
194    0
222    1
      ..
251    0
56     0
126    0
348    0
382    1
Name: Purchased, Length: 300, dtype: int64

In [12]:
y_test

57     0
32     0
17     1
167    0
2      0
      ..
379    1
252    1
320    1
351    0
244    0
Name: Purchased, Length: 100, dtype: int64

In [13]:
x

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [16]:
y_predict=model.predict(x_test)
y_predict

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0], dtype=int64)

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score

In [18]:
acc=accuracy_score(y_test,y_predict)
print(acc)

1.0


In [19]:
cm=confusion_matrix(y_predict,y_test)
cm

array([[60,  0],
       [ 0, 40]], dtype=int64)

In [20]:
prec_score=precision_score(y_test,y_predict)
print(prec_score)

1.0


In [21]:
rec_score=recall_score(y_test,y_predict)
rec_score

1.0

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        60
           1       1.00      1.00      1.00        40

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

