In [28]:
import numpy as np
import pandas as pd
import seaborn as sns

In [29]:
df=sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [30]:
# from sklearn.datasets import load_iris
# iris=load_iris(as_frame=True)
# df1=iris
# df1

In [31]:
# x=df[['sepal_length' ,'sepal_width', 'petal_length' ,'petal_width']]
x=df.iloc[:,:4]
y=df['species']

In [32]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [33]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [34]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=9)

In [35]:
x_train

sepal_length  sepal_width  petal_length  petal_width
109           7.2          3.6           6.1          2.5
7             5.0          3.4           1.5          0.2
17            5.1          3.5           1.4          0.3
100           6.3          3.3           6.0          2.5
86            6.7          3.1           4.7          1.5
..            ...          ...           ...          ...
125           7.2          3.2           6.0          1.8
56            6.3          3.3           4.7          1.6
149           5.9          3.0           5.1          1.8
92            5.8          2.6           4.0          1.2
126           6.2          2.8           4.8          1.8

[112 rows x 4 columns]

In [36]:
x_test

sepal_length  sepal_width  petal_length  petal_width
135           7.7          3.0           6.1          2.3
90            5.5          2.6           4.4          1.2
145           6.7          3.0           5.2          2.3
147           6.5          3.0           5.2          2.0
60            5.0          2.0           3.5          1.0
37            4.9          3.6           1.4          0.1
26            5.0          3.4           1.6          0.4
3             4.6          3.1           1.5          0.2
75            6.6          3.0           4.4          1.4
9             4.9          3.1           1.5          0.1
25            5.0          3.0           1.6          0.2
73            6.1          2.8           4.7          1.2
98            5.1          2.5           3.0          1.1
94            5.6          2.7           4.2          1.3
39            5.1          3.4           1.5          0.2
81            5.5          2.4           3.7          1.0
31            5.4          3.4           1.5          0.4
55            5.7          2.8           4.5          1.3
101           5.8          2.7           5.1          1.9
47            4.6          3.2           1.4          0.2
28            5.2          3.4           1.4          0.2
27            5.2          3.5           1.5          0.2
111           6.4          2.7           5.3          1.9
20            5.4          3.4           1.7          0.2
118           7.7          2.6           6.9          2.3
89            5.5          2.5           4.0          1.3
43            5.0          3.5           1.6          0.6
144           6.7          3.3           5.7          2.5
8             4.4          2.9           1.4          0.2
137           6.4          3.1           5.5          1.8
112           6.8          3.0           5.5          2.1
138           6.0          3.0           4.8          1.8
23            5.1          3.3           1.7          0.5
67            5.8          2.7           4.1          1.0
79            5.7          2.6           3.5          1.0
82            5.8          2.7           3.9          1.2
76            6.8          2.8           4.8          1.4
45            4.8          3.0           1.4          0.3

In [37]:
y_train

109     virginica
7          setosa
17         setosa
100     virginica
86     versicolor
          ...    
125     virginica
56     versicolor
149     virginica
92     versicolor
126     virginica
Name: species, Length: 112, dtype: object

In [38]:
y_test

135     virginica
90     versicolor
145     virginica
147     virginica
60     versicolor
37         setosa
26         setosa
3          setosa
75     versicolor
9          setosa
25         setosa
73     versicolor
98     versicolor
94     versicolor
39         setosa
81     versicolor
31         setosa
55     versicolor
101     virginica
47         setosa
28         setosa
27         setosa
111     virginica
20         setosa
118     virginica
89     versicolor
43         setosa
144     virginica
8          setosa
137     virginica
112     virginica
138     virginica
23         setosa
67     versicolor
79     versicolor
82     versicolor
76     versicolor
45         setosa
Name: species, dtype: object

In [39]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [40]:
x_train

array([[ 1.58442601,  1.12664597,  1.2669428 ,  1.65549463],
       [-1.09139694,  0.68621194, -1.34188585, -1.38193711],
       [-0.96976862,  0.90642896, -1.39859952, -1.24987486],
       [ 0.48977116,  0.46599493,  1.21022913,  1.65549463],
       [ 0.97628443,  0.0255609 ,  0.47295147,  0.33487213],
       [-0.96976862,  1.56707999, -1.11503119, -1.11781261],
       [ 0.48977116, -0.41487312,  0.98337446,  0.73105888],
       [ 0.36814285, -1.95639221,  0.35952413,  0.33487213],
       [-1.5779102 ,  0.68621194, -1.39859952, -1.24987486],
       [-0.36162705, -1.29574117,  0.01924214, -0.19337687],
       [-1.09139694,  0.24577792, -1.51202685, -1.38193711],
       [ 1.82768264, -0.63509014,  1.2669428 ,  0.86312113],
       [ 0.0032579 ,  0.24577792,  0.52966513,  0.73105888],
       [ 0.61139948,  0.24577792,  0.35952413,  0.33487213],
       [-0.60488368,  1.34686298, -1.34188585, -1.38193711],
       [-0.48325536, -1.7361752 ,  0.0759558 ,  0.07074763],
       [ 0.48977116, -0.

In [41]:
x_test

array([[ 2.47679934,  0.09640215,  1.55701988,  1.65279437],
       [-0.22633937, -1.0307614 ,  0.56212884,  0.18598323],
       [ 1.24809993,  0.09640215,  1.03031286,  1.65279437],
       [ 1.00236005,  0.09640215,  1.03031286,  1.25275497],
       [-0.84068907, -2.72150672,  0.03542182, -0.0807097 ],
       [-0.96355901,  1.78714747, -1.19356124, -1.28082791],
       [-0.84068907,  1.22356569, -1.07651523, -0.88078851],
       [-1.33216883,  0.37819303, -1.13503823, -1.14748144],
       [ 1.12522999,  0.09640215,  0.56212884,  0.45267617],
       [-0.96355901,  0.37819303, -1.13503823, -1.28082791],
       [-0.84068907,  0.09640215, -1.07651523, -1.14748144],
       [ 0.51088028, -0.46717963,  0.73769785,  0.18598323],
       [-0.71781913, -1.31255229, -0.2571932 ,  0.05263676],
       [-0.10346942, -0.74897052,  0.44508284,  0.3193297 ],
       [-0.71781913,  1.22356569, -1.13503823, -1.14748144],
       [-0.22633937, -1.59434318,  0.15246782, -0.0807097 ],
       [-0.34920931,  1.

In [42]:
from sklearn.naive_bayes import GaussianNB
nb_model=GaussianNB()
nb_model.fit(x_train,y_train)

GaussianNB()

In [43]:
y_predict=nb_model.predict(x_test)
y_predict

array(['virginica', 'versicolor', 'virginica', 'virginica', 'versicolor',
       'setosa', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'setosa', 'setosa', 'setosa',
       'virginica', 'setosa', 'virginica', 'versicolor', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'setosa'], dtype='<U10')

In [44]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score
acc=accuracy_score(y_test,y_predict)
print(acc)

0.9473684210526315


In [45]:
cm=confusion_matrix(y_predict,y_test)
cm

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  2, 10]], dtype=int64)

In [46]:
prec_score=precision_score(y_test,y_predict,average='macro')
print(prec_score)

0.9444444444444445


In [47]:
rec_score=recall_score(y_test,y_predict,average='macro')
rec_score

0.9487179487179488

In [48]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       1.00      0.85      0.92        13
   virginica       0.83      1.00      0.91        10

    accuracy                           0.95        38
   macro avg       0.94      0.95      0.94        38
weighted avg       0.96      0.95      0.95        38



In [49]:
x_new=[[2.7,3.4,1.7,4.2]]
x_new=sc.fit_transform(x_new)
new_pred=nb_model.predict(x_new)
new_pred

array(['versicolor'], dtype='<U10')