In [27]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [28]:
df = pd.read_csv("train.csv")
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [29]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [30]:
eg = ""
eg = '. '.join(df['title'].head())
print(eg)

House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It. FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart. Why the Truth Might Get You Fired. 15 Civilians Killed In Single US Airstrike Have Been Identified. Iranian woman jailed for fictional unpublished story about woman stoned to death for adultery


In [31]:
import nltk
from nltk.corpus import stopwords

In [32]:
stopword = stopwords.words("english")
print(stopword)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [33]:
eg = eg.lower()
eg

'house dem aide: we didn’t even see comey’s letter until jason chaffetz tweeted it. flynn: hillary clinton, big woman on campus - breitbart. why the truth might get you fired. 15 civilians killed in single us airstrike have been identified. iranian woman jailed for fictional unpublished story about woman stoned to death for adultery'

In [34]:
words = nltk.word_tokenize(eg)
print(words)

['house', 'dem', 'aide', ':', 'we', 'didn', '’', 't', 'even', 'see', 'comey', '’', 's', 'letter', 'until', 'jason', 'chaffetz', 'tweeted', 'it', '.', 'flynn', ':', 'hillary', 'clinton', ',', 'big', 'woman', 'on', 'campus', '-', 'breitbart', '.', 'why', 'the', 'truth', 'might', 'get', 'you', 'fired', '.', '15', 'civilians', 'killed', 'in', 'single', 'us', 'airstrike', 'have', 'been', 'identified', '.', 'iranian', 'woman', 'jailed', 'for', 'fictional', 'unpublished', 'story', 'about', 'woman', 'stoned', 'to', 'death', 'for', 'adultery']


In [35]:
without_stopword = [word for word in words if word not in stopword]
print(without_stopword)

['house', 'dem', 'aide', ':', '’', 'even', 'see', 'comey', '’', 'letter', 'jason', 'chaffetz', 'tweeted', '.', 'flynn', ':', 'hillary', 'clinton', ',', 'big', 'woman', 'campus', '-', 'breitbart', '.', 'truth', 'might', 'get', 'fired', '.', '15', 'civilians', 'killed', 'single', 'us', 'airstrike', 'identified', '.', 'iranian', 'woman', 'jailed', 'fictional', 'unpublished', 'story', 'woman', 'stoned', 'death', 'adultery']


In [36]:
from nltk.stem import WordNetLemmatizer
from nltk.stem import SnowballStemmer

In [48]:
lemmatizer = WordNetLemmatizer()
lemmatized_output = ([lemmatizer.lemmatize(w) for w in without_stopword])
print(lemmatized_output)

['house', 'dem', 'aide', ':', '’', 'even', 'see', 'comey', '’', 'letter', 'jason', 'chaffetz', 'tweeted', '.', 'flynn', ':', 'hillary', 'clinton', ',', 'big', 'woman', 'campus', '-', 'breitbart', '.', 'truth', 'might', 'get', 'fired', '.', '15', 'civilian', 'killed', 'single', 'u', 'airstrike', 'identified', '.', 'iranian', 'woman', 'jailed', 'fictional', 'unpublished', 'story', 'woman', 'stoned', 'death', 'adultery']


In [38]:
without_punctuation = []
for q in without_stopword:
    if(q.isalpha()):
        without_punctuation.append(q)

print(without_punctuation)

['house', 'dem', 'aide', 'even', 'see', 'comey', 'letter', 'jason', 'chaffetz', 'tweeted', 'flynn', 'hillary', 'clinton', 'big', 'woman', 'campus', 'breitbart', 'truth', 'might', 'get', 'fired', 'civilians', 'killed', 'single', 'us', 'airstrike', 'identified', 'iranian', 'woman', 'jailed', 'fictional', 'unpublished', 'story', 'woman', 'stoned', 'death', 'adultery']


In [39]:
lemmatizer = WordNetLemmatizer()
lemmatized_output = ([lemmatizer.lemmatize(w) for w in without_punctuation])
print(lemmatized_output)

['house', 'dem', 'aide', 'even', 'see', 'comey', 'letter', 'jason', 'chaffetz', 'tweeted', 'flynn', 'hillary', 'clinton', 'big', 'woman', 'campus', 'breitbart', 'truth', 'might', 'get', 'fired', 'civilian', 'killed', 'single', 'u', 'airstrike', 'identified', 'iranian', 'woman', 'jailed', 'fictional', 'unpublished', 'story', 'woman', 'stoned', 'death', 'adultery']


In [40]:
stemmed_words = []
stemmer = SnowballStemmer("english")
for word in without_punctuation:
    stemmed_words.append(stemmer.stem(word))

print(stemmed_words)

['hous', 'dem', 'aid', 'even', 'see', 'comey', 'letter', 'jason', 'chaffetz', 'tweet', 'flynn', 'hillari', 'clinton', 'big', 'woman', 'campus', 'breitbart', 'truth', 'might', 'get', 'fire', 'civilian', 'kill', 'singl', 'us', 'airstrik', 'identifi', 'iranian', 'woman', 'jail', 'fiction', 'unpublish', 'stori', 'woman', 'stone', 'death', 'adulteri']


In [41]:
pos_tagged = nltk.pos_tag(stemmed_words)
pos_tagged

[('hous', 'JJ'),
 ('dem', 'NN'),
 ('aid', 'NN'),
 ('even', 'RB'),
 ('see', 'VB'),
 ('comey', 'JJ'),
 ('letter', 'NN'),
 ('jason', 'NN'),
 ('chaffetz', 'NN'),
 ('tweet', 'NN'),
 ('flynn', 'NN'),
 ('hillari', 'VBP'),
 ('clinton', 'NN'),
 ('big', 'JJ'),
 ('woman', 'NN'),
 ('campus', 'NN'),
 ('breitbart', 'NN'),
 ('truth', 'NN'),
 ('might', 'MD'),
 ('get', 'VB'),
 ('fire', 'JJ'),
 ('civilian', 'JJ'),
 ('kill', 'NN'),
 ('singl', 'VBD'),
 ('us', 'PRP'),
 ('airstrik', 'RP'),
 ('identifi', 'JJ'),
 ('iranian', 'JJ'),
 ('woman', 'NN'),
 ('jail', 'NN'),
 ('fiction', 'NN'),
 ('unpublish', 'JJ'),
 ('stori', 'NN'),
 ('woman', 'NN'),
 ('stone', 'VBD'),
 ('death', 'NN'),
 ('adulteri', 'NN')]

In [42]:
sen = nltk.sent_tokenize(eg)
sen

['house dem aide: we didn’t even see comey’s letter until jason chaffetz tweeted it.',
 'flynn: hillary clinton, big woman on campus - breitbart.',
 'why the truth might get you fired.',
 '15 civilians killed in single us airstrike have been identified.',
 'iranian woman jailed for fictional unpublished story about woman stoned to death for adultery']

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [44]:
# assign documents
d0 = 'good boy'
d1 = 'girl good'
d2 = 'boy girl good'

# merge documents into a single corpus
string = [d0, d1, d2]
string

['good boy', 'girl good', 'boy girl good']

In [45]:
# create object
tfidf = TfidfVectorizer()

# get tf-df values
result = tfidf.fit_transform(string)

In [46]:
# Assuming you have already fit_transformed your data using tfidf
print('\nidf values:')
for feature_name, idx in tfidf.vocabulary_.items():
    print(feature_name, ':', tfidf.idf_[idx])



idf values:
good : 1.0
boy : 1.2876820724517808
girl : 1.2876820724517808


In [47]:
# get indexing
print('\nWord indexes:')
print(tfidf.vocabulary_)

# display tf-idf values
print('\ntf-idf value:')
print(result)

# in matrix form
print('\ntf-idf values in matrix form:')
print(result.toarray())


Word indexes:
{'good': 2, 'boy': 0, 'girl': 1}

tf-idf value:
  (0, 0)	0.7898069290660905
  (0, 2)	0.6133555370249717
  (1, 1)	0.7898069290660905
  (1, 2)	0.6133555370249717
  (2, 1)	0.6198053799406072
  (2, 0)	0.6198053799406072
  (2, 2)	0.48133416873660545

tf-idf values in matrix form:
[[0.78980693 0.         0.61335554]
 [0.         0.78980693 0.61335554]
 [0.61980538 0.61980538 0.48133417]]
